[package]
name = "kafka-foo-ing"
version = "0.1.0"
edition = "2021"

[dependencies]
rdkafka = { version = "0.36", features = ["cmake-build", "gssapi", "sasl", "ssl" ] }
thiserror = "1.0"
futures = "0.3"
anyhow = "1"

tokio = { version = "1.0", features = ["full"] }